import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(PROJECT_ROOT, "data", "sampled_fully_labeled_new_version_v1.csv")

OUTPUT_DIR = os.path.join(PROJECT_ROOT, "outputs")
REPORTS_DIR = os.path.join(OUTPUT_DIR, "reports")
FIGURES_DIR = os.path.join(OUTPUT_DIR, "figures")
PREDICTIONS_DIR = os.path.join(OUTPUT_DIR, "predictions")
MODELS_DIR = os.path.join(OUTPUT_DIR, "models")

TEXT_COLUMN = "text_ml_clean"
LABEL_COLUMN = "label"
SPLIT_COLUMN = "split"

LABEL_NAMES = ["CONSTRUCTIVE", "NEUTRAL", "TOXIC", "POSITIVE"]

TFIDF_MAX_FEATURES = 30000
TFIDF_NGRAM_RANGES = {
    "unigram": (1, 1),
    "uni+bigram": (1, 2),
}

MODELS = ["LogisticRegression", "LinearSVC", "MultinomialNB"]

BERT_MODEL_NAME = "tugstugi/bert-base-mongolian-cased"
BERT_TEXT_COLUMN = "text_light_clean"
BERT_MAX_LENGTH = 128
BERT_BATCH_SIZE = 16
BERT_EPOCHS = 100
BERT_LR = 2e-5
BERT_WARMUP_RATIO = 0.1

RANDOM_SEED = 42

CUSTOM_MAX_SEQ_LEN = 128
CUSTOM_MAX_WORD_LEN = 20
CUSTOM_WORD_VOCAB_SIZE = 30000
CUSTOM_CHAR_VOCAB_SIZE = 2000

CUSTOM_CHAR_EMBED_DIM = 50
CUSTOM_CHAR_CNN_FILTERS = 100
CUSTOM_CHAR_CNN_KERNELS = [2, 3, 4, 5, 6, 7]

CUSTOM_WORD_EMBED_DIM = 300
CUSTOM_FUSION_DIM = 512

CUSTOM_LSTM_HIDDEN = 256
CUSTOM_LSTM_LAYERS = 2
CUSTOM_LSTM_DROPOUT = 0.2

CUSTOM_ATTN_HEADS = 4
CUSTOM_ATTN_DROPOUT = 0.1

CUSTOM_CLASSIFIER_HIDDEN = 256
CUSTOM_CLASSIFIER_DROPOUT = 0.3

CUSTOM_EMBED_SPATIAL_DROPOUT = 0.2
CUSTOM_TOKEN_DROPOUT_RATE = 0.1

CUSTOM_BATCH_SIZE = 16
CUSTOM_EPOCHS = 75
CUSTOM_LR = 3e-3
CUSTOM_WEIGHT_DECAY = 0.01
CUSTOM_LABEL_SMOOTHING = 0.1
CUSTOM_GRAD_CLIP = 1.0
CUSTOM_PATIENCE = 3

CUSTOMV2_MAX_SEQ_LEN = 128
CUSTOMV2_MAX_WORD_LEN = 20

CUSTOMV2_CHAR_VOCAB_SIZE = 2000
CUSTOMV2_WORD_VOCAB_SIZE = 30000

CUSTOMV2_CHAR_EMBED_DIM = 64
CUSTOMV2_CHAR_CNN_FILTERS = 128
CUSTOMV2_CHAR_CNN_KERNELS = [2, 3, 4, 5, 6, 7]

CUSTOMV2_WORD_EMBED_DIM = 200

CUSTOMV2_D_MODEL = 384

CUSTOMV2_TRANSFORMER_LAYERS = 4
CUSTOMV2_TRANSFORMER_HEADS = 6
CUSTOMV2_TRANSFORMER_FF_DIM = 1024
CUSTOMV2_TRANSFORMER_DROPOUT = 0.2
CUSTOMV2_TRANSFORMER_ATTN_DROPOUT = 0.1

CUSTOMV2_POOL_HEADS = 4
CUSTOMV2_POOL_DROPOUT = 0.1

CUSTOMV2_CLASSIFIER_HIDDEN = 256
CUSTOMV2_CLASSIFIER_DROPOUT = 0.3

CUSTOMV2_EMBED_DROPOUT = 0.2

CUSTOMV2_BATCH_SIZE = 64
CUSTOMV2_EPOCHS = 200
CUSTOMV2_LR = 8e-4
CUSTOMV2_MIN_LR = 1e-7
CUSTOMV2_WARMUP_FRAC = 0.1
CUSTOMV2_WEIGHT_DECAY = 0.01
CUSTOMV2_LABEL_SMOOTHING = 0.1
CUSTOMV2_GRAD_CLIP = 1.0
CUSTOMV2_PATIENCE = 7

CUSTOMV2_FOCAL_GAMMA = 2.0

CUSTOMV2_SWA_START_FRAC = 0.8
CUSTOMV2_SWA_LR = 5e-4

CUSTOMV2_AUG_WORD_DROP_RATE = 0.10
CUSTOMV2_AUG_WORD_SWAP_RATE = 0.05
CUSTOMV2_AUG_MINORITY_PROB = 0.5
CUSTOMV2_AUG_MAJORITY_PROB = 0.2
CUSTOMV2_MINORITY_LABEL_IDS = [2, 3]

CUSTOMV2_COLLAPSE_CHECK_EPOCH = 5
CUSTOMV2_COLLAPSE_PATIENCE = 3
CUSTOMV2_LR_RESCUE_FACTOR = 2.0
